
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gofroychetqq
{

using System;
    using System.Collections.Generic;
    
public partial class Material
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Material()
    {

        this.Prihod = new HashSet<Prihod>();

        this.Rashod = new HashSet<Rashod>();

    }


    public int MaterialID { get; set; }

    public string Name { get; set; }

    public int MaterialTypeID { get; set; }

    public double MinimumStock { get; set; }



    public virtual MaterialType MaterialType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Prihod> Prihod { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rashod> Rashod { get; set; }

}

}
