

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gofroychetqq
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class etonEntities : DbContext
{
    public etonEntities()
        : base("name=etonEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Material> Material { get; set; }

    public virtual DbSet<MaterialType> MaterialType { get; set; }

    public virtual DbSet<Nakladnaya> Nakladnaya { get; set; }

    public virtual DbSet<Prihod> Prihod { get; set; }

    public virtual DbSet<Rashod> Rashod { get; set; }

    public virtual DbSet<Reason> Reason { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TypeNakladnaya> TypeNakladnaya { get; set; }

    public virtual DbSet<Unit> Unit { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<Supplier> Supplier { get; set; }

    public virtual DbSet<Supply> Supply { get; set; }

    public virtual DbSet<SupplyStatus> SupplyStatus { get; set; }

}

}

