
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gofroychetqq
{

using System;
    using System.Collections.Generic;
    
public partial class Nakladnaya
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Nakladnaya()
    {

        this.Prihod = new HashSet<Prihod>();

        this.Rashod = new HashSet<Rashod>();

    }


    public int NakladnayaID { get; set; }

    public int Number { get; set; }

    public System.DateTime CreateDate { get; set; }

    public int TypeNakladnaya { get; set; }



    public virtual TypeNakladnaya TypeNakladnaya1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Prihod> Prihod { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rashod> Rashod { get; set; }

}

}
