
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gofroychetqq
{

using System;
    using System.Collections.Generic;
    
public partial class Rashod
{

    public int RashodID { get; set; }

    public int MaterialID { get; set; }

    public double Quantity { get; set; }

    public System.DateTime RashodDate { get; set; }

    public int ReasonID { get; set; }

    public int UserID { get; set; }

    public int NakladnayaID { get; set; }



    public virtual Material Material { get; set; }

    public virtual Nakladnaya Nakladnaya { get; set; }

    public virtual Reason Reason { get; set; }

    public virtual User User { get; set; }

}

}
