
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gofroychetqq
{

using System;
    using System.Collections.Generic;
    
public partial class Supply
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supply()
    {

        this.Prihod = new HashSet<Prihod>();

    }


    public int SupplyID { get; set; }

    public int SupplierID { get; set; }

    public int SupplyStatusID { get; set; }

    public System.DateTime SupplyDate { get; set; }

    public string DocumentNumber { get; set; }

    public string Note { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Prihod> Prihod { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual SupplyStatus SupplyStatus { get; set; }

}

}
